import { StatusBar, StyleSheet } from "react-native";
import { Colors } from "../../assets/Colors";
import { FULLVIEW_HEIGHT, FULLVIEW_WIDTH } from "../../Utils/Helper";

export const HomeStyleSheet = StyleSheet.create({
    home:{
        backgroundColor:Colors.bgColor,
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
        gap:20,
        paddingVertical:20
    },
    banner:{
        height:'95%',
        width:FULLVIEW_WIDTH,
        paddingVertical:10,
    },
    imgContainer:{
        width:0.8*FULLVIEW_WIDTH,
        height:'100%',
        borderRadius:10,
        marginHorizontal:0.1*FULLVIEW_WIDTH,
        position:'relative',
    },
    img:{
        position:'absolute',
        top:0,
        left:0,
        width:'100%',
        height:'100%',
        borderRadius:10,
        objectFit:'fill'
    },
    layer:{
        position:'absolute',
        top:0,
        left:0,
        width:'100%',
        height:'100%',
        borderRadius:10,
        backgroundColor:'#000',
        opacity:.7,
    },
    content:{
        width:'100%',
        height:'100%',
        display:'flex',
        justifyContent:'flex-end',
        alignItems:'center',
        padding:15,
        paddingBottom:50
    },
    text:{
        fontFamily:'ExtraBold',
        fontSize:24,
        width:'100%',
        textAlign:'center',
        color:Colors.textColor
    },
    btns:{
        display:'flex',
        flexDirection:'row',
        gap:20,
        justifyContent:'center',
        alignItems:'center',
    },
    btn:{
        display:'flex',
        flexDirection:'row',
        gap:5,
        justifyContent:'center',
        alignItems:'center',
        paddingVertical:5,
        paddingHorizontal:10,
        borderRadius:3,
        text:{
            fontFamily:'Medium',
            color:Colors.textColor,
            fontSize:12,
            textAlign:'center'
        }
    },
    genreText:{
        fontFamily:'Bold',
        color:Colors.secColor,
        fontSize:12,
        textAlign:'center',
        marginBottom:5
    },
    dot:{
        width:3,
        height:3,
        borderRadius:50,
        backgroundColor:Colors.secColor
    },
    rowText:{
        fontFamily:'Bold',
        color:Colors.textColor,
        fontSize:12,
    }
})