import { StyleSheet } from "react-native";
import { Colors } from "../../assets/Colors";
import { FULLVIEW_HEIGHT, FULLVIEW_WIDTH } from "../../Utils/Helper";

export const movieStyleSheet = StyleSheet.create({
    movie:{
        backgroundColor:Colors.bgColor,
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
        gap:20,
        paddingVertical:20
    },
    MD:{
        backgroundColor:Colors.bgColor,
        justifyContent:'flex-start',
        alignItems:'flex-start',
        gap:20,
        paddingBottom:100,
        position:'relative'
    },
    MD_Back:{
        position:'absolute',
        top:20,
        left:20,
        zIndex:5,
        elevation:20,
        backgroundColor:Colors.secColorGold,
        padding:5,
        borderRadius:10
    },
    MD_Banner:{
        width:'100%',
        minHeight:FULLVIEW_HEIGHT,
        position:'relative',
        justifyContent:'center'
    },
    MD_BGImg:{
        position:'absolute',
        top:0,
        left:0,
        width:'100%',
        height:'100%',
        zIndex:0,
        opacity:.2,
        
    },
    MD_Img:{
        width:'60%',
        height:300,
        borderRadius:20,
        objectFit:'cover',
        
    },
    MD_Content:{
        justifyContent:'flex-start',
        alignItems:'flex-start',
        gap:10,
        margin:20,
    },
    MD_Title:{
        fontFamily:'ExtraBold',
        fontSize:18,
        color:Colors.textColor
    },
    MD_ROW:{
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center',
        gap:10
    },
    MD_Stars:{
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center',
        gap:2
    },
    MD_rowText:{
        fontFamily:'Bold',
        fontSize:12,
        color:Colors.textColor
    },
    MD_dot:{
        width:5,
        height:5,
        borderRadius:50,
        backgroundColor:Colors.secColor
    },
    MD_Para:{
        fontFamily:'Bold',
        fontSize:10,
        color:Colors.secColorLight
    },
    MD_Btns:{
        flexDirection:'row',
        gap:20,
        justifyContent:'flex-start',
        alignItems:'center',
        marginTop:20
    },
    MD_Btn:{
        flexDirection:'row',
        gap:10,
        justifyContent:'center',
        alignItems:'center',
        paddingHorizontal:14,
        paddingVertical:7,
        borderRadius:5,
        text:{
            fontFamily:'Bold',
            fontSize:14,
            color:Colors.secColorLight
        }
    }
})